title: Site

pages: default

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text
    width: 1/2

  email:
    label: Email
    type: email
    width: 1/2

  location:
    label: Location
    type: text
    width: 1/2

  occupation:
    label: Occupation
    type: text
    width: 1/2

  employer:
    label: Employer
    type: text
    width: 1/2

  description:
    label: Description
    type:  textarea

  socialFacebook:
    label: Facebook
    type: url
    width: 1/3

  socialTwitter:
    label: Twitter
    type: url
    width: 1/3

  socialGithub:
    label: Github
    type: url
    width: 1/3

  socialLinkedin:
    label: LinkedIn
    type: url
    width: 1/3

  socialDribbble:
    label: Dribbble
    type: url
    width: 1/3
